acceptor:
	g++ -o acceptor_test acceptor_test.cc ../acceptor.cc

socket:
	g++ -o socket_test socket_test.cc ../client/socket.cc

log:
	g++ -o log_test log_test.cc ../log.cc

clean:
	rm acceptor_test socket_test log_test 

